apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: heimdall
  labels:
    app: heimdall
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: heimdall
                port:
                  number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: heimdall
  labels:
    app: heimdall
spec:
  type: ClusterIP
  selector:
    app: heimdall
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  labels:
    app: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
      annotations:
        heimdall.cfg: v1
    spec:
      containers:
        - name: heimdall
          image: ghcr.io/linuxserver/heimdall
          envFrom:
            - configMapRef:
                name: heimdall
          volumeMounts:
            - name: heimdall-config
              mountPath: /config
      volumes:
        - name: heimdall-config
          hostPath:
            path: /mnt/config/heimdall
            type: DirectoryOrCreate

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: heimdall
  labels:
    app: heimdall
data:
  TZ: Europe/London
  PUID: "1000"
  PGID: "1000"
