apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jackett
  labels:
    app: jackett
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /jackett
            pathType: Prefix
            backend:
              service:
                name: jackett
                port:
                  number: 9117

---
apiVersion: v1
kind: Service
metadata:
  name: jackett
  labels:
    app: jackett
spec:
  type: ClusterIP
  selector:
    app: jackett
  ports:
    - port: 9117
      targetPort: 9117

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  labels:
    app: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
      annotations:
        jackett.cfg: v1
    spec:
      containers:
        - name: jackett
          image: linuxserver/jackett:version-v0.18.354
          envFrom:
            - configMapRef:
                name: jackett
          volumeMounts:
            - name: jackett-config
              mountPath: /config          
            - name: jackett-volumes
              mountPath: /downloads
              subPath: downloads
      volumes:
        - name: jackett-config
          hostPath:
            path: /mnt/config/jackett
            type: DirectoryOrCreate
        - name: jackett-volumes
          hostPath:
            path: /mnt/volumes/jackett
            type: DirectoryOrCreate

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jackett
  labels:
    app: jackett
data:
  TZ: Europe/London
  PUID: "1000"
  PGID: "1000"
