apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: overseerr
  labels:
    app: overseerr
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /overseerr
            pathType: Prefix
            backend:
              service:
                name: overseerr
                port:
                  number: 5055

---
apiVersion: v1
kind: Service
metadata:
  name: overseerr
  labels:
    app: overseerr
spec:
  type: ClusterIP
  selector:
    app: overseerr
  ports:
    - port: 5055
      targetPort: 5055

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  labels:
    app: overseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overseerr
  template:
    metadata:
      labels:
        app: overseerr
      annotations:
        overseerr.cfg: v1
    spec:
      containers:
        - name: overseerr
          image: linuxserver/overseerr:version-v1.26.1
          envFrom:
            - configMapRef:
                name: overseerr
          volumeMounts:
            - name: overseerr-config
              mountPath: /config
      volumes:
        - name: overseerr-config
          hostPath:
            path: /home/pi/.config/overseerr
            type: DirectoryOrCreate

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: overseerr
  labels:
    app: overseerr
data:
  TZ: Europe/London
  PUID: "1000"
  PGID: "1000"
