apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  labels:
    app: radarr
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /radarr
            pathType: Prefix
            backend:
              service:
                name: radarr
                port:
                  number: 7878

---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  type: ClusterIP
  selector:
    app: radarr
  ports:
    - port: 7878
      targetPort: 7878

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
      annotations:
        radarr.cfg: v1
    spec:
      containers:
        - name: radarr
          image: linuxserver/radarr:version-3.2.2.5080
          envFrom:
            - configMapRef:
                name: radarr
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: data-volume
              mountPath: /data
      volumes:
        - name: radarr-config
          hostPath:
            path: /home/pi/.config/radarr
            type: DirectoryOrCreate
        - name: data-volume
          hostPath:
            path: /media/storage/volumes/data
            type: DirectoryOrCreate

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr
  labels:
    app: radarr
data:
  TZ: Europe/London
  PUID: "1000"
  PGID: "1000"
