apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  labels:
    app: sonarr
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /sonarr
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  number: 8989

---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    app: sonarr
spec:
  type: ClusterIP
  selector:
    app: sonarr
  ports:
    - port: 8989
      targetPort: 8989

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
      annotations:
        sonarr.cfg: v1
    spec:
      containers:
        - name: sonarr
          image: linuxserver/sonarr:0.6.1343
          envFrom:
            - configMapRef:
                name: sonarr
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: data-volume
              mountPath: /data              
      volumes:
        - name: sonarr-config
          hostPath:
            path: /home/pi/.config/sonarr
            type: DirectoryOrCreate
        - name: data-volume
          hostPath:
            path: /media/storage/volumes/data
            type: DirectoryOrCreate

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarr
  labels:
    app: sonarr
data:
  TZ: Europe/London
  PUID: "1000"
  PGID: "1000"
