apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission
  labels:
    app: transmission
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /transmission
            pathType: Prefix
            backend:
              service:
                name: transmission
                port:
                  number: 9091

---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  labels:
    app: transmission
spec:
  type: ClusterIP
  selector:
    app: transmission
  ports:
    - port: 9091
      targetPort: 9091

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  labels:
    app: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
      annotations:
        transmission.cfg: v1
    spec:
      containers:
        - name: transmission
          image: linuxserver/transmission:version-3.00-r2
          envFrom:
            - configMapRef:
                name: transmission
          volumeMounts:
            - name: transmission-config
              mountPath: /config
            - name: transmission-volume
              mountPath: /downloads
              subPath: downloads
            - name: transmission-volume
              mountPath: /watch
              subPath: watch
      volumes:
        - name: transmission-config
          hostPath:
            path: /home/pi/.config/transmission
            type: DirectoryOrCreate
        - name: transmission-volume
          hostPath:
            path: /media/storage/volumes/data/torrents
            type: DirectoryOrCreate

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission
  labels:
    app: transmission
data:
  TZ: Europe/London
  PUID: "1000"
  PGID: "1000"
  TRANSMISSION_WEB_HOME: /flood-for-transmission/
